# This workflow compiles the audio project with cmake
# Workflow credit to: https://github.com/actions/starter-workflows/issues/196

name: Compile

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on: [push]

# Executes cmake
jobs:
  build-ubuntu:

      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v1
      - name: configure
        run: sudo apt update && sudo apt upgrade && mkdir build && cd build && cmake ..
      - name: build
        run: make
